/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.ActionListener;
import javax.swing.JMenuItem;

/**
 *
 * @author JoseR
 */
public class jPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form jPrincipal
     */
    public jPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCliente = new javax.swing.JMenuItem();
        jMenuItemCasa = new javax.swing.JMenuItem();
        jMenuItemUrb = new javax.swing.JMenuItem();
        jMenuItemGastosExtra = new javax.swing.JMenuItem();
        jMenuReportes = new javax.swing.JMenu();
        jMenuItemReporteGastoExtra = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bluewave-white-backgrounds.jpg"))); // NOI18N

        jMenu1.setText("Opciones");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItemCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItemCliente.setText("Cliente");
        jMenu1.add(jMenuItemCliente);

        jMenuItemCasa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItemCasa.setText("Casa");
        jMenu1.add(jMenuItemCasa);

        jMenuItemUrb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItemUrb.setText("Urbanizacion");
        jMenu1.add(jMenuItemUrb);

        jMenuItemGastosExtra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItemGastosExtra.setText("Gastos Extra");
        jMenu1.add(jMenuItemGastosExtra);

        jMenuBar1.add(jMenu1);

        jMenuReportes.setText("Reportes");
        jMenuReportes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItemReporteGastoExtra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItemReporteGastoExtra.setText("Gastos Extras");
        jMenuReportes.add(jMenuItemReporteGastoExtra);

        jMenuBar1.add(jMenuReportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    public JMenuItem getjMenuItemCliente(){
        return jMenuItemCliente;
    }
    
    public JMenuItem getjMenuItemCasa() {
        return jMenuItemCasa;
    }
    
    public JMenuItem getjMenuItemUrb() {
        return jMenuItemUrb;
    }
    
    public JMenuItem getjMenuItemGastoExtra() {
        return jMenuItemGastosExtra;
    }
    
    public JMenuItem getjMenuItemReporteGastoEx() {
        return jMenuItemReporteGastoExtra;
    }
    
    public void agregarListener(ActionListener action){
        this.jMenuItemCliente.addActionListener(action);
        this.jMenuItemCasa.addActionListener(action);
        this.jMenuItemUrb.addActionListener(action);
        this.jMenuItemGastosExtra.addActionListener(action);
        this.jMenuItemReporteGastoExtra.addActionListener(action);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCasa;
    private javax.swing.JMenuItem jMenuItemCliente;
    private javax.swing.JMenuItem jMenuItemGastosExtra;
    private javax.swing.JMenuItem jMenuItemReporteGastoExtra;
    private javax.swing.JMenuItem jMenuItemUrb;
    private javax.swing.JMenu jMenuReportes;
    // End of variables declaration//GEN-END:variables
}
